// <auto-generated />
namespace DealersTrack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Step1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Step1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611291126374_Step1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
